ebook_metadata:
  title: ༄༅། །བསྟན་འགྲོ་ཡོངས་ལ་ཕན་པའི་ཨོ་རྒྱན་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  sku: SHE-SHAP-10
  layers:
  - book_title
  - author
  - quotation
web_metadata:
  title:
    en: The Book of Emanated Scriptures of Orgyen
    bo: བསྟན་འགྲོ་ཡོངས་ལ་ཕན་པའི་ཨོ་རྒྱན་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 10
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༠
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-10
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-10.epub
  description:
    en: ''
    bo: ''
